// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: squareup/cash/pranadb/notifications/v1/notifications.proto

package notifications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DDLStatementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginatingNodeId int64    `protobuf:"varint,1,opt,name=originating_node_id,json=originatingNodeId,proto3" json:"originating_node_id,omitempty"`
	Sequence          int64    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SchemaName        string   `protobuf:"bytes,3,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Sql               string   `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`
	TableSequences    []uint64 `protobuf:"varint,5,rep,packed,name=table_sequences,json=tableSequences,proto3" json:"table_sequences,omitempty"`
	Kind              string   `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *DDLStatementInfo) Reset() {
	*x = DDLStatementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DDLStatementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLStatementInfo) ProtoMessage() {}

func (x *DDLStatementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLStatementInfo.ProtoReflect.Descriptor instead.
func (*DDLStatementInfo) Descriptor() ([]byte, []int) {
	return file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *DDLStatementInfo) GetOriginatingNodeId() int64 {
	if x != nil {
		return x.OriginatingNodeId
	}
	return 0
}

func (x *DDLStatementInfo) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DDLStatementInfo) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *DDLStatementInfo) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DDLStatementInfo) GetTableSequences() []uint64 {
	if x != nil {
		return x.TableSequences
	}
	return nil
}

func (x *DDLStatementInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type SessionClosedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SessionClosedMessage) Reset() {
	*x = SessionClosedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionClosedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClosedMessage) ProtoMessage() {}

func (x *SessionClosedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClosedMessage.ProtoReflect.Descriptor instead.
func (*SessionClosedMessage) Descriptor() ([]byte, []int) {
	return file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SessionClosedMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_squareup_cash_pranadb_notifications_v1_notifications_proto protoreflect.FileDescriptor

var file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x2f,
	0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x73, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e,
	0x61, 0x64, 0x62, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x76, 0x31, 0x22, 0xce, 0x01, 0x0a, 0x10, 0x44, 0x44, 0x4c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x0e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x35, 0x0a, 0x14, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x42, 0x4b, 0x5a, 0x49,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x75, 0x70, 0x2f, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x73, 0x68,
	0x2f, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescData = file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDesc
)

func file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescData)
	})
	return file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDescData
}

var file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_squareup_cash_pranadb_notifications_v1_notifications_proto_goTypes = []interface{}{
	(*DDLStatementInfo)(nil),     // 0: squareup.cash.pranadb.notifications.v1.DDLStatementInfo
	(*SessionClosedMessage)(nil), // 1: squareup.cash.pranadb.notifications.v1.SessionClosedMessage
}
var file_squareup_cash_pranadb_notifications_v1_notifications_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_squareup_cash_pranadb_notifications_v1_notifications_proto_init() }
func file_squareup_cash_pranadb_notifications_v1_notifications_proto_init() {
	if File_squareup_cash_pranadb_notifications_v1_notifications_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DDLStatementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionClosedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_squareup_cash_pranadb_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_squareup_cash_pranadb_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_squareup_cash_pranadb_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_squareup_cash_pranadb_notifications_v1_notifications_proto = out.File
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_rawDesc = nil
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_goTypes = nil
	file_squareup_cash_pranadb_notifications_v1_notifications_proto_depIdxs = nil
}
