// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: squareup/cash/pranadb/loadrunner/v1/loadrunner.proto

package loadrunner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandJson string `protobuf:"bytes,1,opt,name=command_json,json=commandJson,proto3" json:"command_json,omitempty"`
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandRequest) GetCommandJson() string {
	if x != nil {
		return x.CommandJson
	}
	return ""
}

var File_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto protoreflect.FileDescriptor

var file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDesc = []byte{
	0x0a, 0x34, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x2f,
	0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x72, 0x75, 0x6e, 0x6e,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70,
	0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2e, 0x6c, 0x6f,
	0x61, 0x64, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x11, 0x52, 0x75,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4a, 0x73,
	0x6f, 0x6e, 0x32, 0x71, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x36, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70,
	0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2e, 0x6c, 0x6f,
	0x61, 0x64, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x70, 0x72, 0x61,
	0x6e, 0x61, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x71, 0x75, 0x61,
	0x72, 0x65, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x2f, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64,
	0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescOnce sync.Once
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescData = file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDesc
)

func file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescGZIP() []byte {
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescOnce.Do(func() {
		file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescData = protoimpl.X.CompressGZIP(file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescData)
	})
	return file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDescData
}

var file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_goTypes = []interface{}{
	(*RunCommandRequest)(nil), // 0: squareup.cash.pranadb.loadrunner.v1.RunCommandRequest
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_depIdxs = []int32{
	0, // 0: squareup.cash.pranadb.loadrunner.v1.LoadRunnerService.RunCommand:input_type -> squareup.cash.pranadb.loadrunner.v1.RunCommandRequest
	1, // 1: squareup.cash.pranadb.loadrunner.v1.LoadRunnerService.RunCommand:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_init() }
func file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_init() {
	if File_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_goTypes,
		DependencyIndexes: file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_depIdxs,
		MessageInfos:      file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_msgTypes,
	}.Build()
	File_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto = out.File
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_rawDesc = nil
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_goTypes = nil
	file_squareup_cash_pranadb_loadrunner_v1_loadrunner_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LoadRunnerServiceClient is the client API for LoadRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoadRunnerServiceClient interface {
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type loadRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadRunnerServiceClient(cc grpc.ClientConnInterface) LoadRunnerServiceClient {
	return &loadRunnerServiceClient{cc}
}

func (c *loadRunnerServiceClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/squareup.cash.pranadb.loadrunner.v1.LoadRunnerService/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadRunnerServiceServer is the server API for LoadRunnerService service.
type LoadRunnerServiceServer interface {
	RunCommand(context.Context, *RunCommandRequest) (*emptypb.Empty, error)
}

// UnimplementedLoadRunnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLoadRunnerServiceServer struct {
}

func (*UnimplementedLoadRunnerServiceServer) RunCommand(context.Context, *RunCommandRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}

func RegisterLoadRunnerServiceServer(s *grpc.Server, srv LoadRunnerServiceServer) {
	s.RegisterService(&_LoadRunnerService_serviceDesc, srv)
}

func _LoadRunnerService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadRunnerServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squareup.cash.pranadb.loadrunner.v1.LoadRunnerService/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadRunnerServiceServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoadRunnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "squareup.cash.pranadb.loadrunner.v1.LoadRunnerService",
	HandlerType: (*LoadRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCommand",
			Handler:    _LoadRunnerService_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "squareup/cash/pranadb/loadrunner/v1/loadrunner.proto",
}
