// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: squareup/cash/pranadb/service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaterializedViewRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SchemaName string `protobuf:"bytes,1,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetMaterializedViewRequest) Reset() {
	*x = GetMaterializedViewRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareup_cash_pranadb_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaterializedViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterializedViewRequest) ProtoMessage() {}

func (x *GetMaterializedViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_squareup_cash_pranadb_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterializedViewRequest.ProtoReflect.Descriptor instead.
func (*GetMaterializedViewRequest) Descriptor() ([]byte, []int) {
	return file_squareup_cash_pranadb_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaterializedViewRequest) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *GetMaterializedViewRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMaterializedViewResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMaterializedViewResponse) Reset() {
	*x = GetMaterializedViewResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareup_cash_pranadb_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaterializedViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaterializedViewResponse) ProtoMessage() {}

func (x *GetMaterializedViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_squareup_cash_pranadb_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaterializedViewResponse.ProtoReflect.Descriptor instead.
func (*GetMaterializedViewResponse) Descriptor() ([]byte, []int) {
	return file_squareup_cash_pranadb_service_proto_rawDescGZIP(), []int{1}
}

var File_squareup_cash_pranadb_service_proto protoreflect.FileDescriptor

var file_squareup_cash_pranadb_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x2f,
	0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2e,
	0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x51, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x98, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x61, 0x6e, 0x61,
	0x44, 0x42, 0x12, 0x8c, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x69, 0x65, 0x77, 0x12, 0x39, 0x2e, 0x73, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x75, 0x70, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e, 0x61,
	0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70,
	0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70, 0x2f, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x75, 0x70,
	0x2f, 0x63, 0x61, 0x73, 0x68, 0x2f, 0x70, 0x72, 0x61, 0x6e, 0x61, 0x64, 0x62, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_squareup_cash_pranadb_service_proto_rawDescOnce sync.Once
	file_squareup_cash_pranadb_service_proto_rawDescData = file_squareup_cash_pranadb_service_proto_rawDesc
)

func file_squareup_cash_pranadb_service_proto_rawDescGZIP() []byte {
	file_squareup_cash_pranadb_service_proto_rawDescOnce.Do(func() {
		file_squareup_cash_pranadb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_squareup_cash_pranadb_service_proto_rawDescData)
	})
	return file_squareup_cash_pranadb_service_proto_rawDescData
}

var file_squareup_cash_pranadb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_squareup_cash_pranadb_service_proto_goTypes = []interface{}{
	(*GetMaterializedViewRequest)(nil),  // 0: squareup.cash.pranadb.service.GetMaterializedViewRequest
	(*GetMaterializedViewResponse)(nil), // 1: squareup.cash.pranadb.service.GetMaterializedViewResponse
}
var file_squareup_cash_pranadb_service_proto_depIdxs = []int32{
	0, // 0: squareup.cash.pranadb.service.PranaDB.GetMaterializedView:input_type -> squareup.cash.pranadb.service.GetMaterializedViewRequest
	1, // 1: squareup.cash.pranadb.service.PranaDB.GetMaterializedView:output_type -> squareup.cash.pranadb.service.GetMaterializedViewResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_squareup_cash_pranadb_service_proto_init() }
func file_squareup_cash_pranadb_service_proto_init() {
	if File_squareup_cash_pranadb_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_squareup_cash_pranadb_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaterializedViewRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_squareup_cash_pranadb_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaterializedViewResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_squareup_cash_pranadb_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_squareup_cash_pranadb_service_proto_goTypes,
		DependencyIndexes: file_squareup_cash_pranadb_service_proto_depIdxs,
		MessageInfos:      file_squareup_cash_pranadb_service_proto_msgTypes,
	}.Build()
	File_squareup_cash_pranadb_service_proto = out.File
	file_squareup_cash_pranadb_service_proto_rawDesc = nil
	file_squareup_cash_pranadb_service_proto_goTypes = nil
	file_squareup_cash_pranadb_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PranaDBClient is the client API for PranaDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PranaDBClient interface {
	GetMaterializedView(ctx context.Context, in *GetMaterializedViewRequest, opts ...grpc.CallOption) (*GetMaterializedViewResponse, error)
}

type pranaDBClient struct {
	cc grpc.ClientConnInterface
}

func NewPranaDBClient(cc grpc.ClientConnInterface) PranaDBClient {
	return &pranaDBClient{cc}
}

func (c *pranaDBClient) GetMaterializedView(ctx context.Context, in *GetMaterializedViewRequest, opts ...grpc.CallOption) (*GetMaterializedViewResponse, error) {
	out := new(GetMaterializedViewResponse)
	err := c.cc.Invoke(ctx, "/squareup.cash.pranadb.service.PranaDB/GetMaterializedView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PranaDBServer is the server API for PranaDB service.
type PranaDBServer interface {
	GetMaterializedView(context.Context, *GetMaterializedViewRequest) (*GetMaterializedViewResponse, error)
}

// UnimplementedPranaDBServer can be embedded to have forward compatible implementations.
type UnimplementedPranaDBServer struct {
}

func (*UnimplementedPranaDBServer) GetMaterializedView(context.Context, *GetMaterializedViewRequest) (*GetMaterializedViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaterializedView not implemented")
}

func RegisterPranaDBServer(s *grpc.Server, srv PranaDBServer) {
	s.RegisterService(&_PranaDB_serviceDesc, srv)
}

func _PranaDB_GetMaterializedView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMaterializedViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PranaDBServer).GetMaterializedView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/squareup.cash.pranadb.service.PranaDB/GetMaterializedView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PranaDBServer).GetMaterializedView(ctx, req.(*GetMaterializedViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PranaDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "squareup.cash.pranadb.service.PranaDB",
	HandlerType: (*PranaDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMaterializedView",
			Handler:    _PranaDB_GetMaterializedView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "squareup/cash/pranadb/service.proto",
}
