name: "Hourly Integration Tests"
on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - force-integration-tests # Push this branch to force this job to run
jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go
          restore-keys: |
            ${{ runner.os }}-go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Init Hermit
        run: |
          ./bin/hermit env --raw >> $GITHUB_ENV
          ./bin/hermit install
      - name: Build
        run: go build ./...
      - name: SQLTests
        run: go test -race -count=1 -timeout 20m -failfast -p 1 -tags confluent ./sqltest
        if: ${{ always() }}
      - name: Kafka tests using RedPanda and SegmentIO Kafka client
        run: go test -race -count=1 -timeout 20m -failfast -p 1 -tags integration ./kafkatest -- -kafka-provider=redpanda
        if: ${{ always() }}
      - name: Kafka tests using RedPanda and Confluent Kafka client
        run: go test -race -count=1 -timeout 20m -failfast -p 1 -tags confluent,integration ./kafkatest -- -kafka-provider=redpanda
        if: ${{ always() }}
      - name: Kafka tests using Kafka and SegmentIO Kafka client
        run: go test -race -count=1 -timeout 20m -failfast -p 1 -tags integration ./kafkatest -- -kafka-provider=kafka
        if: ${{ always() }}
  slack-on-fail:
    runs-on: [ self-hosted, linux ]
    needs: [ integration ]
    if: always() && (needs.integration.result == 'failure' || needs.integration.result == 'error')
    steps:
      - run: git clone --depth 1 https://github.com/squareup/github-actions --branch v1 --single-branch
      - uses: ./github-actions/slack-on-fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TEXT: Integration tests failed.
