name: slack-notify
on: status
jobs:
  slack-notify:
    runs-on: [ self-hosted, linux ]
    if: ${{ contains(github.event.branches.*.name, 'main') && (github.event.state == 'failure' || github.event.state == 'error')}}
    steps:
      - run: git clone --depth 1 https://github.com/squareup/github-actions --branch v1 --single-branch
      - uses: ./github-actions/slack-on-fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TEXT: Main build failing on CI.
